# version: '3.8'

# if you are getting a table not found error use this in command line
# docker-compose exec server php artisan migrate

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: laravel_server
    volumes:
      - ./backend:/var/www/html
      - ./backend/storage:/var/www/html/storage
    environment:
      - DB_HOST=database
      - DB_DATABASE=gallerydb
      - DB_USERNAME=root
      - DB_PASSWORD=1234
      - DB_PORT=3306
    restart: always
    ports:
      - 8000:80
    depends_on:
      - database

  database:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=gallerydb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
