name: Deploy Laravel Application

on:
  push:
    branches: [main]

jobs:
  Build-Laravel-And-Push-Dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run PHPUnit Tests
        run: |
          cd backend
          composer install
          php artisan key:generate
          php artisan config:clear
          php artisan test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/laravel-app:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/laravel-app:latest

  Deploy-Laravel-Docker:
    needs: Build-Laravel-And-Push-Dockerhub
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Stop and remove existing container
            docker stop laravel_server || true
            docker rm laravel_server || true

            # Create and prepare storage directory structure
            sudo mkdir -p /var/www/html/storage
            sudo mkdir -p /var/www/html/storage/framework/{cache,sessions,views}
            sudo mkdir -p /var/www/html/storage/logs
            sudo chmod -R 777 /var/www/html/storage

            # Pull the latest image
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/laravel-app:latest

            # Run the new container with proper permissions
            docker run -d \
              --name laravel_server \
              -p 8000:80 \
              -v /var/www/html/storage:/var/www/html/storage \
              -e APP_ENV=production \
              -e APP_DEBUG=true \
              -e APP_KEY=base64:${{ secrets.APP_KEY }} \
              -e LOG_CHANNEL=stderr \
              -e DB_HOST=${{ secrets.DB_HOST }} \
              -e DB_DATABASE=${{ secrets.DB_DATABASE }} \
              -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              ${{ secrets.DOCKER_HUB_USERNAME }}/laravel-app:latest

            # Wait for container to initialize
            sleep 15

            # Generate application key if not passed via env
            docker exec laravel_server bash -c "[ -z \"$APP_KEY\" ] && php artisan key:generate --force || true"

            # Set proper permissions
            docker exec laravel_server chown -R www-data:www-data /var/www/html/storage
            docker exec laravel_server chmod -R 775 /var/www/html/storage
            docker exec laravel_server chmod -R 775 /var/www/html/bootstrap/cache

            # Run database migrations
            docker exec laravel_server php artisan migrate --force || true

            # Clear and cache configurations
            docker exec laravel_server php artisan config:clear
            docker exec laravel_server php artisan config:cache
            docker exec laravel_server php artisan view:clear
            docker exec laravel_server php artisan route:clear

            # Check container status
            echo "Container status:"
            docker ps -a

            # Check application health
            echo "Application health check:"
            curl -I http://localhost:8000 || true

            # Check logs
            echo "Last 50 lines of logs:"
            docker logs laravel_server --tail 50
