name: Deploy Laravel Application

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, ctype, xml, dom, fileinfo, sqlite, pdo_sqlite

      - name: Install dependencies
        run: |
          cd backend
          composer install --no-interaction --prefer-dist
          cp .env.example .env
          php artisan key:generate

      - name: Run tests
        run: |
          cd backend
          php artisan config:clear
          php artisan test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/laravel-app:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/laravel-app:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Cleanup previous deployment
            docker stop laravel_server || true
            docker rm laravel_server || true

            # Prepare directories
            sudo mkdir -p /var/www/html/storage
            sudo mkdir -p /var/www/html/storage/framework/{cache,sessions,views}
            sudo mkdir -p /var/www/html/storage/logs
            sudo chmod -R 777 /var/www/html/storage

            # Pull new image
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/laravel-app:latest

            # Run container with production settings
            docker run -d \
              --name laravel_server \
              -p 8000:80 \
              -v /var/www/html/storage:/var/www/html/storage \
              -e APP_ENV=production \
              -e APP_DEBUG=false \
              -e APP_KEY=base64:${{ secrets.APP_KEY }} \
              -e LOG_CHANNEL=stderr \
              -e DB_HOST=${{ secrets.DB_HOST }} \
              -e DB_DATABASE=${{ secrets.DB_HOST }} \
              -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              ${{ secrets.DOCKER_HUB_USERNAME }}/laravel-app:latest

            # Wait for container to initialize
            sleep 20

            # Execute setup commands inside container
            docker exec laravel_server bash -c "
              chown -R www-data:www-data /var/www/html/storage
              chmod -R 775 /var/www/html/storage
              chmod -R 775 /var/www/html/bootstrap/cache
              php artisan config:clear
              php artisan config:cache
              php artisan view:cache
              php artisan route:cache
              php artisan migrate --force
            "

            # Verify deployment
            echo "Checking application health..."
            curl -I http://localhost:8000 || true
            echo "Container logs:"
            docker logs laravel_server --tail 100
