name: Deploy Laravel Application

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/laravel-app:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/laravel-app:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Stop and remove old container
            docker stop laravel_server || true
            docker rm laravel_server || true

            # Create storage directories
            sudo mkdir -p /var/www/html/storage
            sudo mkdir -p /var/www/html/storage/framework/{cache,sessions,views}
            sudo mkdir -p /var/www/html/storage/logs
            sudo chmod -R 777 /var/www/html/storage

            # Pull the image
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/laravel-app:latest

            # Run new container
            docker run -d \
              --name laravel_server \
              -p 8000:80 \
              -v /var/www/html/storage:/var/www/html/storage \
              -e APP_ENV=production \
              -e APP_DEBUG=false \
              -e APP_KEY=base64:${{ secrets.APP_KEY }} \
              -e DB_HOST=${{ secrets.DB_HOST }} \
              -e DB_DATABASE=${{ secrets.DB_DATABASE }} \
              -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              ${{ secrets.DOCKER_HUB_USERNAME }}/laravel-app:latest

            # Wait for startup
            sleep 15

            # Run migrations and optimize
            docker exec laravel_server php artisan migrate --force
            docker exec laravel_server php artisan optimize

            # Fix permissions
            docker exec laravel_server chown -R www-data:www-data /var/www/html/storage
            docker exec laravel_server chmod -R 775 /var/www/html/storage

            # Verify deployment
            echo "=== Deployment Checks ==="
            docker exec laravel_server php artisan route:list
            curl -I http://localhost:8000 || echo "Local check failed"
