name: Deploy Laravel Application

on:
  push:
    branches: [main]

env:
  DB_CONNECTION: sqlite
  DB_DATABASE: ":memory:"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, ctype, xml, dom, fileinfo, sqlite, pdo_sqlite
          coverage: none

      - name: Prepare test environment
        run: |
          cd backend
          cp .env.example .env.testing
          echo "APP_KEY=base64:testkey123456789012345678901234567890" >> .env.testing
          echo "APP_ENV=testing" >> .env.testing
          echo "CACHE_DRIVER=array" >> .env.testing
          echo "SESSION_DRIVER=array" >> .env.testing
          composer install --no-interaction

      - name: Run tests
        run: |
          cd backend
          php artisan config:clear
          php artisan test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/laravel-app:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/laravel-app:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Stop existing container
            docker stop laravel_server || true
            docker rm laravel_server || true

            # Setup storage
            sudo mkdir -p /var/www/html/storage
            sudo mkdir -p /var/www/html/storage/framework/{cache,sessions,views}
            sudo mkdir -p /var/www/html/storage/logs
            sudo chmod -R 777 /var/www/html/storage

            # Pull image
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/laravel-app:latest

            # Run container with proper error reporting
            docker run -d \
              --name laravel_server \
              -p 8000:80 \
              -v /var/www/html/storage:/var/www/html/storage \
              -e APP_ENV=production \
              -e APP_DEBUG=true \
              -e APP_KEY=base64:${{ secrets.APP_KEY }} \
              -e LOG_CHANNEL=stderr \
              -e DB_HOST=${{ secrets.DB_HOST }} \
              -e DB_DATABASE=${{ secrets.DB_DATABASE }} \
              -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              ${{ secrets.DOCKER_HUB_USERNAME }}/laravel-app:latest

            # Wait for startup
            sleep 20

            # Run setup commands
            docker exec laravel_server bash -c "
              chown -R www-data:www-data /var/www/html/storage
              chmod -R 775 /var/www/html/storage
              php artisan config:clear
              php artisan cache:clear
              php artisan view:clear
              php artisan route:clear
              php artisan migrate --force
            "

            # Verify deployment
            echo "=== Error Logs ==="
            docker exec laravel_server tail -n 50 /var/log/apache2/error.log
            echo "=== Laravel Logs ==="
            docker exec laravel_server tail -n 50 /var/www/html/storage/logs/laravel.log
            echo "=== Route List ==="
            docker exec laravel_server php artisan route:list
